[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  port = 8889
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PATCH, OPTIONS"

[[headers]]
  for = "/dashboard/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
